config/routes.rb
Gymrat::Application.routes.draw do
  get "climber/index"
  get "climber/show"
  
  match 'kinds', :controller=>'walls', :action => 'get_drop_down_options'
  
  post "/climbing_centres/:climbing_centre_id/walls/:id" => "walls#vote_up", :constraints => {:commit => "upVote"}
  
  resources :climbing_centres do
    resources :walls, :except => :index do
      member do
        get :climbed_it
      end
    end
  end
  root :to => 'home#index', :defaults => {:id => '4f3083c05cf429195f000004'}
  
  namespace "admin" do
    match '/' => 'admin#index'
  end

  devise_for :users

  

end

app/models/climbing_centre.rb
class ClimbingCentre
  include Mongoid::Document
  #include Mongo::Voteable

  field :name, type: String
  field :city, type: String
  validates :name, :city, :presence => true, :uniqueness => true, :length =>{:maximum=>250}
  has_and_belongs_to_many :users
  embeds_many :walls
end

app/controllers/climbing_centres_controller.rb
class ClimbingCentresController < ApplicationController
  before_filter :only_if_admin, :except => [:index, :show]
  # GET /climbing_centres
  # GET /climbing_centres.json
  def index
    @climbing_centres = ClimbingCentre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @climbing_centres }
    end
  end

  # GET /climbing_centres/1
  # GET /climbing_centres/1.json
  def show
    @climbing_centre = ClimbingCentre.find(params[:id])
    # kaminarri @walls = @climbing_centre.walls.page(params[:page]).per(3)
   @walls = @climbing_centre.walls.order_by('pt', :des)
   
   @walls = @walls.paginate(:per_page => 15, :page  => params[:page])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @climbing_centre }
    end
  end

  # GET /climbing_centres/new
  # GET /climbing_centres/new.json
  def new
    
    @climbing_centre = ClimbingCentre.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @climbing_centre }
    end
  end

  # GET /climbing_centres/1/edit
  def edit
    @climbing_centre = ClimbingCentre.find(params[:id])
  end

  # POST /climbing_centres
  # POST /climbing_centres.json
  def create
    @climbing_centre = ClimbingCentre.new(params[:climbing_centre])

    respond_to do |format|
      if @climbing_centre.save
        format.html { redirect_to @climbing_centre, notice: 'Climbing centre was successfully created.' }
        format.json { render json: @climbing_centre, status: :created, location: @climbing_centre }
      else
        format.html { render action: "new" }
        format.json { render json: @climbing_centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /climbing_centres/1
  # PUT /climbing_centres/1.json
  def update
    @climbing_centre = ClimbingCentre.find(params[:id])

    respond_to do |format|
      if @climbing_centre.update_attributes(params[:climbing_centre])
        format.html { redirect_to @climbing_centre, notice: 'Climbing centre was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @climbing_centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climbing_centres/1
  # DELETE /climbing_centres/1.json
  def destroy
    @climbing_centre = ClimbingCentre.find(params[:id])
    @climbing_centre.destroy

    respond_to do |format|
      format.html { redirect_to climbing_centres_url }
      format.json { head :ok }
    end
  end
end

app/helpers/climbing_centres_helper.rb
module ClimbingCentresHelper
end

app/views/climbing_centres/_form.html.erb
<%= form_for(@climbing_centre) do |f| %>
  <% if @climbing_centre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climbing_centre.errors.count, "error") %> prohibited this climbing_centre from being saved:</h2>

      <ul>
      <% @climbing_centre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climbing_centres/_walls.html.erb
<h1><%= "Listing #{@climbing_centre.name} walls" %></h1>

<%= will_paginate @walls %>

<table>
  <tr>
	<th>Vote Points</th>
	<th>Wall Number</th>
    <th>Kind</th>
    <th>Grade</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<a id="test" href="#">asdfs</a>
<% @walls.each do |wall| %>
  <tr>
	<td id="<%=wall.id%>"><%= wall.pt %></td>
	<td><%= wall.number %></td>
    <td><%= wall.kind %></td>
    <td><%= wall.grade %></td>
    <td><%= link_to 'Show', climbing_centre_wall_path(@climbing_centre,wall)  %></td>
    <td><%= link_to 'Vote Up !',"#",:wall_id => wall.id, :centre_id => wall.climbing_centre.id, :class => "voteUp" if hasnt_voted?(wall)%></td>
    <td><%= link_to 'I climbed it', climbed_it_climbing_centre_wall_path(wall.climbing_centre, wall) if hasnt_climbed_this?(wall) %></td>
    <td><%= link_to 'Edit', edit_climbing_centre_wall_path(wall.climbing_centre, wall) if current_user.try(:admin?)%></td>
    <td><%= (link_to 'Destroy', climbing_centre_wall_path(wall.climbing_centre, wall), confirm: 'Are you sure?', method: :delete) if current_user.try(:admin?) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wall', new_climbing_centre_wall_path(@climbing_centre) if current_user.try(:admin?)%>

<%= link_to 'Edit', edit_climbing_centre_path(@climbing_centre) if current_user.try(:admin?) %>
<%= link_to 'Back', climbing_centres_path %>

app/views/climbing_centres/edit.html.erb
<h1>Editing climbing_centre</h1>

<%= render 'form' %>

<%= link_to 'Show', @climbing_centre %> |
<%= link_to 'Back', climbing_centres_path %>

app/views/climbing_centres/index.html.erb
<h1>Listing climbing_centres</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @climbing_centres.each do |climbing_centre| %>
  <tr>
    <td><%= climbing_centre.name %></td>
    <td><%= climbing_centre.city %></td>
    <td><%= link_to 'Show', climbing_centre %></td>
    <td><%= link_to 'Edit', edit_climbing_centre_path(climbing_centre) if current_user.try(:admin?) %></td>
    <td><%= link_to 'Destroy', climbing_centre, confirm: 'Are you sure?', method: :delete if current_user.try(:admin?) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Climbing centre', new_climbing_centre_path if current_user.try(:admin?) %>

app/views/climbing_centres/new.html.erb
<h1>New climbing_centre</h1>

<%= render 'form' %>

<%= link_to 'Back', climbing_centres_path %>

app/views/climbing_centres/show.html.erb
<%= render 'walls' %>