config/routes.rb
Gymrat::Application.routes.draw do
  get "climber/index"
  get "climber/show"
  
  match 'kinds', :controller=>'walls', :action => 'get_drop_down_options'
  
  post "/climbing_centres/:climbing_centre_id/walls/:id" => "walls#vote_up", :constraints => {:commit => "upVote"}
  
  resources :climbing_centres do
    resources :walls, :except => :index do
      member do
        get :climbed_it
      end
    end
  end
  root :to => 'home#index', :defaults => {:id => '4f3083c05cf429195f000004'}
  
  namespace "admin" do
    match '/' => 'admin#index'
  end

  devise_for :users

  

end

app/models/wall.rb
class Wall
  include Mongoid::Document
  #include Mongo::Voteable
  
  embedded_in :climbing_centre
  has_and_belongs_to_many :users
  
  field :kind, type: String
  field :grade, type: String
  field :color, type: String
  field :number, type: Integer
  field :pt, type: Integer
  field :voters, type: Array
  FGrades = %w[5 5+ 6A 6A+ 6B 6B+ 6C 6C+ 7A 7A+ 7B 7B+ 8A 8A+ 8B 8B+ 9A 9A+]
  BGrades = %w[V0 V0+ V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15]
  Kinds = ['Boulder', 'Leading', 'Top Rope']
  JSONFGrades = "[{\"label\":\"5\",\"value\":\"5\"},{\"label\":\"5+\",\"value\":\"5+\"},{\"label\":\"6A\",\"value\":\"6A\"},{\"label\":\"6A+\",\"value\":\"6A+\"},{\"label\":\"6B\",\"value\":\"6B\"},{\"label\":\"6B+\",\"value\":\"6B+\"},{\"label\":\"6C\",\"value\":\"6C\"},{\"label\":\"6C+\",\"value\":\"6C+\"},{\"label\":\"7A\",\"value\":\"7A\"},{\"label\":\"7A+\",\"value\":\"7A+\"},{\"label\":\"7B\",\"value\":\"7B\"},{\"label\":\"7B+\",\"value\":\"7B+\"},{\"label\":\"8A\",\"value\":\"8A\"},{\"label\":\"8A+\",\"value\":\"8A+\"},{\"label\":\"8B\",\"value\":\"8B\"},{\"label\":\"8B+\",\"value\":\"8B+\"},{\"label\":\"9A\",\"value\":\"9A\"},{\"label\":\"9A+\",\"value\":\"9A+\"}]"
  JSONBGrades = "[{\"label\":\"V0\",\"value\":\"V0\"},{\"label\":\"V0+\",\"value\":\"V0+\"},{\"label\":\"V1\",\"value\":\"V1\"},{\"label\":\"V2\",\"value\":\"V2\"},{\"label\":\"V3\",\"value\":\"V3\"},{\"label\":\"V4\",\"value\":\"V4\"},{\"label\":\"V5\",\"value\":\"V5\"},{\"label\":\"V6\",\"value\":\"V6\"},{\"label\":\"V7\",\"value\":\"V7\"},{\"label\":\"V8\",\"value\":\"V8\"},{\"label\":\"V9\",\"value\":\"V9\"},{\"label\":\"V10\",\"value\":\"V10\"},{\"label\":\"V11\",\"value\":\"V11\"},{\"label\":\"V12\",\"value\":\"V12\"},{\"label\":\"V13\",\"value\":\"V13\"},{\"label\":\"V14\",\"value\":\"V14\"},{\"label\":\"15\",\"value\":\"15\"}]"
  validates :number, :presence => true
  validates :kind, :inclusion => Kinds, :presence  => true
  validates :grade, :inclusion => BGrades, :presence => true, :if => Proc.new { kind == 'Boulder' }
  validates :grade, :inclusion => FGrades, :presence => true, :unless => Proc.new { kind == 'Boulder' }
  def self.json
    json = ""
    BGrades.each_with_index{|x,index| json <<'{"'+"label"+'":'+'"'+"#{x}"+'","value":'+"#{index}},"}
    json.chop!
    X.insert 0,"["
    X << "]"
    X
  end
  # set points for each vote
  #voteable self, :up => +1, :down => -1, :index => true  
  #voteable
  def vote(direction, user_id)
    if (voters)
      return false if voters.include? user_id
    end
    case direction
    when :up
      push(:voters, user_id)
      inc(:pt, 1)
    when :down
      points -= 1 
    else
      raise ArgumentError, 'Vote is not up or down'
    end
  end
     
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_filter :only_if_admin, :except => [:index, :show, :new,:climbed_it,:vote_up]
  before_filter :current_user? , :only => [:climbed_it,:vote_up]
  # GET /walls
  # GET /walls.json
  def index
    centre_id = params[:climbing_centre_id]
    @walls = ClimbingCentre.find(centre_id).walls.page(params[:page]).per(3)
    @centre = ClimbingCentre.find(centre_id).name

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @walls }
    end
  end

  # GET /walls/1
  # GET /walls/1.json
  def show
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wall }
    end
  end

  # GET /walls/new
  # GET /walls/new.json
  def new
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wall }
    end
  end

  # GET /walls/1/edit
  def edit
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])
  end

  # POST /walls
  # POST /walls.json
  def create
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.create!(params[:wall])

    respond_to do |format|
      if @wall.save
        format.html { redirect_to climbing_centre_path(@centre), notice: 'Wall was successfully created.' }
        format.json { render json: @wall, status: :created, location: @wall }
      else
        format.html { render action: "new" }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /walls/1
  # PUT /walls/1.json
  def update
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])

    respond_to do |format|
      if @wall.update_attributes(params[:wall])
        format.html { redirect_to climbing_centre_wall_path(@centre, @wall), notice: 'Wall was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @wall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walls/1
  # DELETE /walls/1.json
  def destroy
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])
    @wall.destroy

    respond_to do |format|
      format.html { redirect_to climbing_centre_path(@centre) }
      format.json { head :ok }
    end
  end
  
  def climbed_it
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])    
    redirect_to root_url, :notice => current_user.climbed_it(@wall) ? "Added to your tick-list !" : "Allready on your tick-list"
  end
  
  # POST with an up vote parameter
  def vote_up
    @centre = ClimbingCentre.find(params[:climbing_centre_id])
    @wall = @centre.walls.find(params[:id])
    @wall.vote(:up, current_user.id)

    respond_to do |format|
        format.json { render json: @wall}
    end
  end
  
  def get_drop_down_options
   
    if params[:selected].present?
      #[{"label":"Option 1","value":1},{"label":"Option 2","value":2}]
      @grades = (params[:selected] == "Boulder" ? Wall::JSONBGrades : Wall::JSONFGrades)
    else
      @grades = '[]'
    end
    render :text => @grades 
  end
  
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/walls/_form.html.erb
<%= debug params %>
<%= form_for([@wall.climbing_centre, @wall]) do |f| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation"> 
      <h2><%= pluralize(@wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% @wall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div id="kind" class="field">
    <%= f.label :kind %><br />
    <%= f.select :kind, Wall::Kinds, :input_html => {:rel => "/kinds"} %>
  </div>
  <div class="field">
    <%= f.label :wall_number %><br />
    <%= f.text_field :number%>
  </div>
 <div id="gradelist" class="field">
	<%= f.label :grade  %><br />
	<%= f.select :grade, Wall::BGrades %>
  </div> 

  <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

app/views/walls/edit.html.erb
<h1>Editing wall</h1>

<%= render 'form' %>

<%= link_to 'Show', climbing_centre_walls_path(@wall) %> |
<%= link_to 'Back', climbing_centre_walls_path %>

app/views/walls/grades_by_kind.js.erb
$("#gradelist").html(escape_javascript('<label for="gbabe_grade">Grade</label></br><select id="gbabe" name="gbabe"><option value="5">5</option>
<option value="5">5</option>
<option value="6A">6A</option>
<option value="6A">6A</option>
<option value="6B">6B</option>
<option value="6B">6</option>
<option value="6C">6C</option>
<option value="6C">6C</option>
<option value="7A">7A</option>
<option value="7A">7A</option>
<option value="7B">7B</option>
<option value="7B">7B</option>
<option value="8A">8A</option>
<option value="8A">8A</option>
<option value="8B">8B</option>
<option value="8B">8</option>
<option value="9A">9A</option>
<option value="9A">9A</option></select>'));

app/views/walls/index.html.erb
<h1><%= "Listing #{@centre} walls" %></h1>

<%= paginate @walls %>

<table>
  <tr>
    <th>Kind</th>
    <th>Grade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @walls.each do |wall| %>
  <tr>
    <td><%= wall.kind %></td>
    <td><%= wall.climbing_centre.name %></td>
    <td><%= wall.grade %></td>
    <td><%= link_to 'Show', climbing_centre_wall_path(wall.climbing_centre, wall) %></td>
    <td><%= link_to 'Edit', edit_climbing_centre_wall_path(wall.climbing_centre, wall) %></td>
    <td><%= link_to 'Destroy', climbing_centre_wall_path(wall.climbing_centre, wall), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wall', new_climbing_centre_wall_path %>

app/views/walls/new.html.erb
<h1>New wall</h1>

<%= render 'form' %>

<%= link_to 'Back', climbing_centre_walls_path %>

app/views/walls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kind:</b>
  <%= @wall.kind %>
</p>
<p>
  <b>Voters:</b>
  <%= @wall.voters %>
</p>

<p>
  <b>Grade:</b>
  <%= @wall.grade %>
</p>


<%= link_to 'Edit', edit_climbing_centre_wall_path(@centre, @wall) %> |
<%= link_to 'Back', climbing_centre_walls_path %>